# 使用 3.8 版的設定檔，通常新版本會有新的功能，並支援新的設定參數
version: "3.8"
name: roger-h2-compose # 可自訂 docker-compose 的名稱
# 定義 service 的區塊，一個 service 設定可以用來啟動多個 container
services:
  # 定義一個叫 springboot_app 的 service
  springboot_app:
    image: sobadrush/springboot-h2-img:v1
    container_name: my-springboot-h2
    platform: linux/amd64
    restart: no
    ports:
      - "18080:8080"
      - "18787:8787"
    environment:
      - SPRING_CONFIG_LOCATION=/app/spring-configs/
      - SPRING_PROFILE_ACTIVE=dev
      - TZ=Asia/Taipei
    volumes:
      - ./spring_settings/application.yaml:/app/spring-configs/application.yaml # 將 spring 設定檔 volume 到 container 中
  # 定義一個叫 nginx 的 service (Reverse-Proxy)
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: no
    volumes:
      - ./nginx_setting/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7795:80"