############################################################################
# command：
#    $ docker-compose -f docker-compose-prometheus.yaml up -d
#
# 【Prometheus】http://localhost:9090/
# 【Prometheus Targets 查看 job】http://172.20.10.2:9090/targets
# 【node-exporter】http://localhost:9100/
#
############################################################################
version: "3.8"
name: roger-prometheus-compose # 可自訂 docker-compose 的名稱
services:
  prometheus_app:
    image: prom/prometheus:latest
    container_name: my-prometheus
    # platform: linux/amd64
    restart: no
    ports:
      - "9091:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus_settings/prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 主要配置文件
      - ./prometheus_settings/rules/:/etc/prometheus/rules/ # 告警規則
      - ./prometheus-job/:/usr/local/prometheus/groups/prometheus-job/ # 若為 Linux 環境下，可以把 . 改為 $PWD
      - ./node-exporter-job/:/usr/local/prometheus/groups/node-exporter-job/
      - ./redis-exporter-job/:/usr/local/prometheus/groups/redis-exporter-job/ # redis-exporter 監看 Redis

#  node-exporter_app:
#    image: prom/node-exporter:latest
#    container_name: my-node-exporter
#    # platform: linux/amd64
#    restart: no
#    ports:
#      - "9100:9100"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana/grafana
    container_name: my-grafana
    # platform: linux/amd64
    restart: no
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus_app

  my_redis:
    image: "redis:latest"
    container_name: "my-redis-gpa"
    ports:
      - "16379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: "my-redis-exporter"
    restart: unless-stopped
    command: # ref. https://blog.csdn.net/manba_24/article/details/123008746
      - "-redis.addr=my-redis-gpa:6379" # 直接設定 redis-exporter 連線的 redis 位置 (此處使用 container name)
      # - "-redis.password=sa12345" # 直接設定 redis-exporter 連線的 redis 的密碼
    expose: # 僅能讓此 docker-compose 內的 container 們使用 (ref. https://blog.myctw.cc/post/df5.html)
      - 9121
    ports: # 可用 Host 機器的 ip + 9121 port 訪問
      - "9121:9121"
    depends_on:
      - my_redis