-- 新增部門資料
INSERT INTO DEPT_TB (DNAME, LOC) VALUES ('財務部', '臺灣台北');
INSERT INTO DEPT_TB (DNAME, LOC) VALUES ('研發部', '臺灣新竹');
INSERT INTO DEPT_TB (DNAME, LOC) VALUES ('業務部', '美國紐約');
INSERT INTO DEPT_TB (DNAME, LOC) VALUES ('生管部', '中國上海');

-- 新增員工資料
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('KING', 'PRESIDENT', '1981-11-17', 1);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('BLAKE', 'MANAGER', '1981-05-01', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('CLARK', 'MANAGER', '1981-01-09', 1);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('JONES', 'MANAGER', '1981-04-02', 2);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('MARTIN', 'SALESMAN', '1981-09-28', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('ALLEN', 'SALESMAN', '1981-02-02', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('TURNER', 'SALESMAN', '1981-09-28', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('JAMES', 'CLERK', '1981-12-03', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('WARD', 'SALESMAN', '1981-02-22', 3);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('FORD', 'ANALYST', '1981-12-03', 2);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('SMITH', 'CLERK', '1980-12-17', 2);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('SCOTT', 'ANALYST', '1981-12-09', 2);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('ADAMS', 'CLERK', '1983-01-12', 2);
INSERT INTO EMP_TB (ENAME, JOB, HIREDATE, DEPTNO) VALUES ('MILLER', 'CLERK', '1982-01-23', 1);