server:
  port: 8080
  servlet:
    context-path: /RogerReverseProxyTest
spring:
  profiles:
    default: dev # 未指定，會使用 dev 作為預設 profile
    active: dev # 啟動 dev profile
  banner:
    charset: utf-8
    location: classpath:banner.txt
  # JSP 設置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # H2 Database
  h2:
    console:
      enabled: true # 啟用 H2 的 web-console (http://localhost:8080/RogerReverseProxyTest/h2-console/)
      settings:
        web-allow-others: true # 允許非這台 Server的人也可以訪問 H2-Console
  datasource:
    url: jdbc:h2:mem:MyH2DB # h2 database 連接位址(In-Memory)
    # url: jdbc:h2:file:./MyH2DB;AUTO_SERVER=TRUE # h2 database 連接位址(file)
    driver-class-name: org.h2.Driver # 配置 driver
    username: sa # database 用戶名
    password: sa123456 # database 密碼
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # 關閉自動建表
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      encoding: utf-8
      schema-locations: classpath:./Database_init/Create_H2_TABLE_Script.sql
      data-locations: classpath:./Database_init/Insert_H2_TABLE_Script.sql
      continue-on-error: false
logging:
    level:
      org.hibernate.type.descriptor.sql: trace # 顯示 SQL 參數
application: # 以下是自訂參數
  email: default@gmail.com

---

### Develop ###
spring:
  config:
    activate:
      on-profile: dev
management: # Spring Actuator 監控(http://127.0.0.1:7001/my-actuator/health / http://127.0.0.1:7001/my-actuator/env)
  server:
    address: 127.0.0.1
    port: 7001
  endpoints:
    web:
      base-path: "/my-actuator"
      exposure:
        # include: health,info,beans,conditions,env
        include: "*" # 全開
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
application: # 以下是自訂參數
  email: dev@gmail.com
  domain: domain-dev
  servers:
    - ip: '127.0.0.1'
      path: "${application.domain}/dev-path-1"
    - ip: '127.0.0.2'
      path: '${application.domain}/dev-path-2'
    - ip: '127.0.0.3'
      path: "${application.domain}/dev-path-3"
  purchase-info: # java 物件會自動將 - 轉為 _
    name: "Vacuum Cleaner"
    price: 3.00
    quantity: 7

---

### Production ###
spring:
  config:
    activate:
      on-profile: prod
application: # 以下是自訂參數
  email: prod@gmail.com
  domain: domain-prod
  servers:
    - ip: '192.168.0.1'
      path: "${application.domain}/prod-path-1"
    - ip: '192.168.0.2'
      path: '${application.domain}/prod-path-2'
    - ip: '192.168.0.3'
      path: '${application.domain}/prod-path-3'