### 測試 @ResponseStatus -「自訂 404-NotFound」
GET localhost:8080/RogerReverseProxyTest/TestResponseStatusController/helloResponseStatus?empName=RogerLo


### 測試 @ResponseStatus -「自訂 自訂 200-Success」
POST http://localhost:8080/RogerReverseProxyTest/TestResponseStatusController/helloResponseStatus200
Content-Type: application/x-www-form-urlencoded

empName=RogerLo


### 測試 @ResponseStatus -「500 ERROR」，故意送空字串 empName
GET http://localhost:8080/RogerReverseProxyTest/TestResponseStatusController/helloResponseStatus500?empName=


### 測試觸發 @ExceptionHandler
GET http://localhost:8080/RogerReverseProxyTest/TestExtendsBaseController/testTriggerExceptionHandler
Accept: application/json


### 測試 @Valid 驗證 RequestBody
POST http://localhost:8080/RogerReverseProxyTest/TestValidController/getDeptData1
Content-Type: application/json

{
  "deptNo": 9527,
  "deptName": "飛彈部",
  "deptLoc": "桃園龍潭"
}


### 測試 @Valid 驗證 RequestBody - 測試故意放空值
POST http://localhost:8080/RogerReverseProxyTest/TestValidController/getDeptData1
Content-Type: application/json

{
  "deptNo": "999",
  "deptName": "飛彈部3",
  "deptLoc": "桃園龍潭"
}


### 測試 @Valid 驗證 RequestBody - 測試故意放空值(使用 BindingResult)
POST http://localhost:8080/RogerReverseProxyTest/TestValidController/getDeptData2
Content-Type: application/json

{
  "deptNo": "999",
  "deptName": "飛彈部3",
  "deptLoc": "桃園龍潭"
}